### ISSUE TITLE
Support external temperature sensor

### ISSUE THREAD

**Issue by Misiu** [cmroche/greeclimate#33]
Hi there,
I'm not sure if this is the correct way to ask for such a feature, but I think the library must support it before adding it to HA.
I have a Gree air conditioner, I was able to add it to HA without any problem, but my living room with a kitchenette is quite big, so I'd like to use an external temperature sensor that is placed on another side of the room.
I found a custom integration that supports an external temperature sensor (https://github.com/RobHofmann/HomeAssistant-GreeClimateComponent), but I hope this can be added to your library and your integration.

**Comment by cmroche** [comment]
Hi @Misiu this feature is already present.

However it is only supported by certain firmwares. If you are using Home Assistant add `greeclimate: debug` to your `logging` section and copy the logs to this issue. I can check if the firmware is one of the known supported models/versions.

**Comment by Misiu** [comment]
I'll add that and report back.
My current workaround is to use automation to turn on/off the device.

```
  alias: Turn on
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.temperatura_salon
    for: 00:01:10
    above: '24.3'
  condition: []
  action:
  - service: climate.turn_on
    target:
      entity_id: climate.1eba913f
  - service: notify.persistent_notification
    data:
      title: Klima
      message: Klima włączona
  mode: single
- id: '1627477931708'
  alias: Turn off
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.temperatura_salon
    below: '23.8'
    for: 00:01:10
  condition: []
  action:
  - service: climate.turn_off
    target:
      entity_id: climate.1eba913f
  mode: single
```

Ideally, this should be handled via config, for example, this can be set in a generic thermostat (https://www.home-assistant.io/integrations/generic_thermostat/#target_sensor).
If this isn't supported by a specific device/firmware version maybe this can be added to the integration, so it could be handled on the integration level?
